name: Build & Deploy Category Service

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  get-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag-version.outputs.tag }}
    steps:
      - name: Set output
        id: get-tag-version
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/master ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=dev" >> $GITHUB_OUTPUT
          fi

  build-category-service:
    runs-on: ubuntu-22.04
    needs: [get-tag]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npx vitest run

      - name: Build Service
        run: npm run build || echo "No build step needed"

  publish-on-docker:
    needs: [build-category-service]
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    uses: Breizhsport-2025-cube-3/breizhsport-infra/.github/workflows/publish_on_docker.yml@main
    secrets:
      tags: ${{ secrets.DOCKER_USERNAME }}/breizhsport-category:${{ needs.get-tag.outputs.tag }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}