name: Build & Deploy Category Service

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build-category-service:
    runs-on: ubuntu-22.04
    steps:
      # Étape 1 : Checkout du code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Étape 2 : Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Étape 3 : Installation des dépendances
      - name: Install Dependencies
        run: npm install

      # Étape 4 : Build du service (si nécessaire)
      - name: Build Service
        run: npm run build || echo "No build step needed"

  publish-on-docker:
    needs: [build-category-service]
    if: github.ref == 'refs/heads/master'
    uses: Breizhsport-2025-cube-3/breizhsport-infra/.github/workflows/publish_on_docker.yml@main
    secrets:
      tags: ${{ secrets.DOCKER_USERNAME }}/breizhsport-category:v0.1
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
